# Generated by Django 3.2.16 on 2023-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20230705_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employername',
            name='last_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
